# Generated by Django 3.2.7 on 2021-09-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ユーザアイコン'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='ユーザランキング'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0, verbose_name='ユーザ点数'),
        ),
    ]
