# Generated by Django 3.2.7 on 2021-09-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='点数更新日時'),
        ),
    ]
