# Generated by Django 3.2.7 on 2021-09-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210919_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='ユーザアイコン'),
        ),
    ]
