# Generated by Django 3.2.7 on 2021-09-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(default='icon/default.jpg', upload_to='icon/', verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='ランキング'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0, verbose_name='点数'),
        ),
    ]
